export { default as HomeLayout } from "./HomeLayout"
export { default as Landing } from "./landing/Landing"
export { default as Category } from "./category/Category"
export { default as Checkout } from "./checkout/Checkout"
export { default as Error } from "./error/Error"
export { default as SingleProduct } from "./singleProduct/SingleProduct"